[theme]
base = "dark"
primaryColor = "#FB923C"
backgroundColor = "#1C0F0D"
secondaryBackgroundColor = "#3A1A14"
textColor = "#FFF7ED"
font = "sans serif"

[server]
maxUploadSize = 500
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
